### ISSUE TITLE
Temperatur und Luftfeuchtigkeit auf 0

### ISSUE THREAD

**Issue by sohnkarlsruhe** [tmeidinger/homebridge-luftdaten#2]
Nutze die Soft und Hardware von Luftdaten. Auf der Website des Sensors stehen die Werte unter aktuelle Werte, in der Home App und in Protokoll steht aber nur Node1 getCurrentTemperature/Hudimity 0/0
Was kann ich tun?

**Comment by sohnkarlsruhe** [comment]
Habe gerade herausgefunden, dass nur die Werte es DHT22 in HomeKit übernommen werden, gibt es eine Möglichkeit auch von den anderen Temperaturfühlern Werte zu übernehmen? z.B. BME280

**Comment by tmeidinger** [comment]
Ich habe leider keinen BME280 hier. Welche Werte werden vom Sensor über http://ip/data.json geliefert?
